import { db } from '../../config/database.js';
import { executives, stocks } from '../schema/index.js';
import { eq } from 'drizzle-orm';

/**
 * Executive seed data for 25 Canadian pilot stocks.
 * 3-5 executives per stock with realistic titles, career history, and education.
 * Roles: CEO, CFO, COO, VP Exploration, VP Operations, CTO, etc.
 */

interface ExecutiveSeed {
  ticker: string;
  executives: {
    name: string;
    title: string;
    yearsAtCompany: number;
    previousCompanies: string[];
    education: string;
    specialization: string;
    socialLinkedin: string | null;
    socialTwitter: string | null;
  }[];
}

const executiveSeedData: ExecutiveSeed[] = [
  {
    ticker: 'NXE',
    executives: [
      {
        name: 'Leigh Curyer',
        title: 'Chief Executive Officer',
        yearsAtCompany: 10.5,
        previousCompanies: ['Southern Cross Resources', 'Heathgate Resources', 'BHP Billiton'],
        education: 'MBA, University of Adelaide',
        specialization: 'Uranium Mining & Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Benjamin Salter',
        title: 'Chief Financial Officer',
        yearsAtCompany: 4.2,
        previousCompanies: ['Cameco Corporation', 'KPMG', 'Deloitte'],
        education: 'CPA, CFA, University of Saskatchewan',
        specialization: 'Mining Finance & Capital Markets',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Troy Boisjoli',
        title: 'Vice President, Operations & Project Development',
        yearsAtCompany: 7.8,
        previousCompanies: ['Cameco Corporation', 'AREVA Resources'],
        education: 'B.Eng Mining Engineering, University of Alberta',
        specialization: 'Underground Mining Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Susannah Pierce',
        title: 'Vice President, Regulatory & Stakeholder Relations',
        yearsAtCompany: 5.1,
        previousCompanies: ['Shell Canada', 'Canadian Association of Petroleum Producers'],
        education: 'MA Political Science, University of Calgary',
        specialization: 'Regulatory Affairs & Indigenous Relations',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'ARIS',
    executives: [
      {
        name: 'Neil Woodyer',
        title: 'Chief Executive Officer',
        yearsAtCompany: 6.3,
        previousCompanies: ['Endeavour Mining', 'Semafo Inc.', 'Hatch Ltd.'],
        education: 'MBA, London Business School',
        specialization: 'Gold Mining Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'David Sandoval',
        title: 'Chief Financial Officer',
        yearsAtCompany: 4.1,
        previousCompanies: ['Gran Colombia Gold', 'Ernst & Young Colombia'],
        education: 'CPA, Universidad de los Andes',
        specialization: 'Latin American Mining Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Ana Maria Sanchez',
        title: 'Vice President, Exploration',
        yearsAtCompany: 3.5,
        previousCompanies: ['Continental Gold', 'AngloGold Ashanti'],
        education: 'M.Sc Geology, Universidad Nacional de Colombia',
        specialization: 'Epithermal Gold Deposits',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'LUN',
    executives: [
      {
        name: 'Peter Rockandel',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 8.2,
        previousCompanies: ['Barrick Gold', 'Rio Tinto', 'Teck Resources'],
        education: 'MBA, Queen\'s University; B.Eng Mining, UBC',
        specialization: 'Base Metals Mining & Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Teitur Poulsen',
        title: 'Chief Financial Officer',
        yearsAtCompany: 5.5,
        previousCompanies: ['Maersk Group', 'PricewaterhouseCoopers'],
        education: 'M.Sc Economics, Copenhagen Business School',
        specialization: 'Corporate Finance & Risk Management',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Juan Covarrubias',
        title: 'Chief Operating Officer',
        yearsAtCompany: 6.0,
        previousCompanies: ['BHP Billiton Chile', 'Antofagasta Minerals'],
        education: 'B.Eng Mining, Universidad de Chile',
        specialization: 'Copper Operations & Processing',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Michael Amm',
        title: 'Senior Vice President, Technical Services',
        yearsAtCompany: 9.3,
        previousCompanies: ['Rio Tinto', 'SNC-Lavalin'],
        education: 'P.Eng, B.Eng Metallurgy, McGill University',
        specialization: 'Metallurgical Engineering & Process Optimization',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Annie Henriksson',
        title: 'Vice President, People & Culture',
        yearsAtCompany: 3.8,
        previousCompanies: ['Boliden AB', 'Sandvik Mining'],
        education: 'MBA, Stockholm School of Economics',
        specialization: 'Human Resources & Organizational Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'FM',
    executives: [
      {
        name: 'Tristan Pascall',
        title: 'Chief Executive Officer',
        yearsAtCompany: 12.4,
        previousCompanies: ['AngloGold Ashanti', 'Gold Fields'],
        education: 'MBA, University of Cape Town',
        specialization: 'Large-Scale Copper Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Ryan MacWilliam',
        title: 'Chief Financial Officer',
        yearsAtCompany: 3.7,
        previousCompanies: ['Hudbay Minerals', 'BMO Capital Markets'],
        education: 'CPA, CFA, Ivey Business School',
        specialization: 'Mining Finance & Debt Restructuring',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Simon Vetter',
        title: 'Chief Operating Officer, Americas',
        yearsAtCompany: 8.9,
        previousCompanies: ['Teck Resources', 'Codelco'],
        education: 'B.Eng Mining, Universidad de Concepcion',
        specialization: 'Open-Pit Copper Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Juliet Wall',
        title: 'General Counsel & Corporate Secretary',
        yearsAtCompany: 6.5,
        previousCompanies: ['Osler, Hoskin & Harcourt LLP', 'Barrick Gold'],
        education: 'JD, University of Toronto',
        specialization: 'Mining Law & Corporate Governance',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'TKO',
    executives: [
      {
        name: 'Stuart McDonald',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 14.2,
        previousCompanies: ['Teck Resources', 'Highland Valley Copper'],
        education: 'B.Eng Mining, UBC',
        specialization: 'Copper Mining & Heap Leach Technology',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Bryce Farcey',
        title: 'Chief Financial Officer',
        yearsAtCompany: 5.3,
        previousCompanies: ['Imperial Metals', 'KPMG Vancouver'],
        education: 'CPA, Simon Fraser University',
        specialization: 'Mining Financial Management',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'John McManus',
        title: 'Vice President, Operations',
        yearsAtCompany: 11.0,
        previousCompanies: ['Teck Resources', 'BHP Billiton'],
        education: 'B.Eng Mechanical Engineering, BCIT',
        specialization: 'Mill Operations & Processing',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'ERO',
    executives: [
      {
        name: 'David Strang',
        title: 'Chief Executive Officer',
        yearsAtCompany: 8.6,
        previousCompanies: ['Nyrstar', 'Xstrata', 'Falconbridge'],
        education: 'MBA, IMD Business School',
        specialization: 'Copper & Zinc Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Wayne Drier',
        title: 'Chief Financial Officer',
        yearsAtCompany: 5.2,
        previousCompanies: ['Yamana Gold', 'Deloitte Brazil'],
        education: 'CPA, University of Toronto',
        specialization: 'Brazilian Mining Finance & Tax',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Makko DeFilippo',
        title: 'President & Chief Operating Officer',
        yearsAtCompany: 7.4,
        previousCompanies: ['MCSA Mining Complex', 'Vale S.A.'],
        education: 'B.Eng Mining, Universidade Federal de Minas Gerais',
        specialization: 'Underground Copper Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Andrea Nardiello',
        title: 'Vice President, Exploration',
        yearsAtCompany: 4.8,
        previousCompanies: ['Lundin Mining Brazil', 'Votorantim Metais'],
        education: 'M.Sc Geology, Universidade de Sao Paulo',
        specialization: 'IOCG Copper-Gold Deposits',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'CS',
    executives: [
      {
        name: 'John Cariou',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 5.8,
        previousCompanies: ['HudBay Minerals', 'Rio Tinto', 'Quadra Mining'],
        education: 'MBA, Queen\'s University; P.Eng',
        specialization: 'Copper Operations & Mine Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Raman Randhawa',
        title: 'Chief Financial Officer',
        yearsAtCompany: 3.9,
        previousCompanies: ['Teck Resources', 'EY Mining'],
        education: 'CPA, CFA, University of British Columbia',
        specialization: 'Mining Corporate Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Brad Mercer',
        title: 'Senior Vice President, Operations',
        yearsAtCompany: 7.2,
        previousCompanies: ['Pinto Valley Mine', 'Freeport-McMoRan'],
        education: 'B.Eng Mining, Colorado School of Mines',
        specialization: 'Open-Pit Mining & Concentrator Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Gregg Bush',
        title: 'Chief Operating Officer',
        yearsAtCompany: 4.5,
        previousCompanies: ['Mantos Copper', 'BHP Chile'],
        education: 'B.Eng Chemical Engineering, Universidad de Chile',
        specialization: 'SX-EW Processing & Copper Cathode Production',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'MAG',
    executives: [
      {
        name: 'George Paspalas',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 9.1,
        previousCompanies: ['Kirkland Lake Gold', 'Newcrest Mining', 'BHP Billiton'],
        education: 'B.Eng Mining, University of Queensland',
        specialization: 'Silver-Gold Mine Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Larry Taddei',
        title: 'Chief Financial Officer',
        yearsAtCompany: 11.3,
        previousCompanies: ['First Majestic Silver', 'PricewaterhouseCoopers'],
        education: 'CPA, University of British Columbia',
        specialization: 'Silver Mining Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Peter Megaw',
        title: 'Chief Exploration Officer',
        yearsAtCompany: 18.5,
        previousCompanies: ['IMDEX', 'Universidad de Guanajuato'],
        education: 'Ph.D Geology, University of Arizona',
        specialization: 'Carbonate Replacement Deposits & Mexican Geology',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'FVI',
    executives: [
      {
        name: 'Jorge Ganoza',
        title: 'President, Chief Executive Officer & Director',
        yearsAtCompany: 18.7,
        previousCompanies: ['Compania de Minas Buenaventura', 'Volcan Compania Minera'],
        education: 'MBA, INCAE Business School; B.Eng Mining, Pontificia Universidad Catolica del Peru',
        specialization: 'Precious Metals Mining in Latin America',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Luis Ganoza',
        title: 'Chief Financial Officer',
        yearsAtCompany: 14.2,
        previousCompanies: ['Goldman Sachs', 'J.P. Morgan'],
        education: 'MBA, Wharton School; B.Sc Finance, Universidad del Pacifico',
        specialization: 'Investment Banking & Mining Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'David Whittle',
        title: 'Chief Operating Officer',
        yearsAtCompany: 4.6,
        previousCompanies: ['Barrick Gold', 'Newmont Mining', 'Endeavour Mining'],
        education: 'B.Eng Mining, Western Australian School of Mines',
        specialization: 'Multi-Mine Operations Management',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'WPM',
    executives: [
      {
        name: 'Randy Smallwood',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 17.3,
        previousCompanies: ['Wheaton River Minerals', 'Goldcorp', 'Westmin Resources'],
        education: 'MBA, Queen\'s University; B.Eng Geological Engineering, UBC',
        specialization: 'Precious Metals Streaming & Royalties',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Gary Brown',
        title: 'Senior Vice President & Chief Financial Officer',
        yearsAtCompany: 15.8,
        previousCompanies: ['Goldcorp', 'KPMG'],
        education: 'CPA, University of British Columbia',
        specialization: 'Streaming Finance & Capital Allocation',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Haytham Hodaly',
        title: 'Senior Vice President, Corporate Development',
        yearsAtCompany: 12.4,
        previousCompanies: ['BMO Capital Markets', 'CIBC World Markets'],
        education: 'MBA, Rotman School of Management',
        specialization: 'M&A & Streaming Deal Structuring',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Patrick Drouin',
        title: 'Senior Vice President & Chief Operating Officer',
        yearsAtCompany: 8.9,
        previousCompanies: ['Osisko Mining', 'Agnico Eagle'],
        education: 'P.Eng, B.Eng Mining, Ecole Polytechnique de Montreal',
        specialization: 'Mine Engineering & Technical Evaluation',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'AEM',
    executives: [
      {
        name: 'Ammar Al-Joundi',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 7.5,
        previousCompanies: ['Barrick Gold', 'Agnico Eagle (Board)', 'Royal Bank of Canada'],
        education: 'MBA, Ivey Business School; B.Comm, University of Manitoba',
        specialization: 'Gold Mining Strategy & Corporate Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Dominique Girard',
        title: 'Executive Vice President & Chief Operating Officer',
        yearsAtCompany: 6.2,
        previousCompanies: ['Canadian Malartic (Osisko)', 'ArcelorMittal Mining'],
        education: 'P.Eng, B.Eng Mining, Universite Laval',
        specialization: 'Large-Scale Open-Pit Gold Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Jamie Porter',
        title: 'Senior Vice President, Finance & Chief Financial Officer',
        yearsAtCompany: 5.8,
        previousCompanies: ['Kirkland Lake Gold', 'Deloitte'],
        education: 'CPA, Queen\'s University',
        specialization: 'Mining Financial Reporting & Controls',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Guy Gosselin',
        title: 'Executive Vice President, Exploration',
        yearsAtCompany: 11.6,
        previousCompanies: ['Virginia Mines', 'Geological Survey of Canada'],
        education: 'Ph.D Geology, Universite du Quebec',
        specialization: 'Greenstone Belt Gold Exploration',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Carol Plummer',
        title: 'Senior Vice President, Technical Services',
        yearsAtCompany: 4.3,
        previousCompanies: ['Newmont Mining', 'SRK Consulting'],
        education: 'P.Eng, M.Eng Geotechnical, University of Alberta',
        specialization: 'Mine Planning & Geotechnical Engineering',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'OR',
    executives: [
      {
        name: 'Jason Attew',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 4.8,
        previousCompanies: ['BMO Capital Markets', 'GMP Securities'],
        education: 'MBA, Schulich School of Business',
        specialization: 'Royalty & Streaming Business Models',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Elif Fiona Louden',
        title: 'Vice President, Finance & Chief Financial Officer',
        yearsAtCompany: 3.5,
        previousCompanies: ['Wheaton Precious Metals', 'EY'],
        education: 'CPA, McGill University',
        specialization: 'Royalty Finance & Tax Planning',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Alexandre Tardimond',
        title: 'Vice President, Corporate Development',
        yearsAtCompany: 5.9,
        previousCompanies: ['National Bank Financial', 'Osisko Mining'],
        education: 'MBA, HEC Montreal',
        specialization: 'Royalty Acquisitions & Deal Origination',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'ELD',
    executives: [
      {
        name: 'George Burns',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 8.4,
        previousCompanies: ['Goldcorp', 'Kinross Gold', 'Placer Dome'],
        education: 'P.Eng, B.Eng Mining, University of British Columbia',
        specialization: 'International Gold Mine Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Philip Yee',
        title: 'Executive Vice President & Chief Financial Officer',
        yearsAtCompany: 6.7,
        previousCompanies: ['Endeavour Mining', 'BDO Canada'],
        education: 'CPA, CFA, University of Toronto',
        specialization: 'Mining Finance & Investor Relations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Joe Dick',
        title: 'Executive Vice President & Chief Operating Officer',
        yearsAtCompany: 10.1,
        previousCompanies: ['Barrick Gold Turkey', 'Teck Resources'],
        education: 'B.Eng Mining, Queen\'s University',
        specialization: 'Heap Leach & Flotation Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Simon Griffiths',
        title: 'Senior Vice President, Exploration & Growth',
        yearsAtCompany: 5.3,
        previousCompanies: ['Kirkland Lake Gold', 'Newmont Greece'],
        education: 'M.Sc Economic Geology, James Cook University',
        specialization: 'Porphyry & Epithermal Gold-Copper Deposits',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'SII',
    executives: [
      {
        name: 'Whitney George',
        title: 'Chief Executive Officer',
        yearsAtCompany: 5.6,
        previousCompanies: ['Sprott Asset Management', 'Royce & Associates', 'Gabelli Funds'],
        education: 'MBA, Columbia Business School',
        specialization: 'Precious Metals Investment Management',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Kevin Hibbert',
        title: 'Chief Financial Officer',
        yearsAtCompany: 4.2,
        previousCompanies: ['CI Financial', 'KPMG'],
        education: 'CPA, CFA, University of Western Ontario',
        specialization: 'Asset Management Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'John Ciampaglia',
        title: 'Senior Managing Director, Sprott Asset Management',
        yearsAtCompany: 7.8,
        previousCompanies: ['iShares Canada', 'Clarica Life Insurance'],
        education: 'MBA, Rotman School of Management',
        specialization: 'ETF & Physical Trust Product Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'BTO',
    executives: [
      {
        name: 'Clive Johnson',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 17.2,
        previousCompanies: ['Bema Gold', 'Pangea Goldfields'],
        education: 'B.Sc Geology, University of British Columbia',
        specialization: 'International Gold Mine Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Mike Cinnamond',
        title: 'Senior Vice President & Chief Financial Officer',
        yearsAtCompany: 6.4,
        previousCompanies: ['Endeavour Mining', 'Deloitte Vancouver'],
        education: 'CPA, University of British Columbia',
        specialization: 'Mining Finance & Cost Optimization',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Bill Shero',
        title: 'Senior Vice President & Chief Operating Officer',
        yearsAtCompany: 9.3,
        previousCompanies: ['Kinross Gold', 'Goldcorp'],
        education: 'P.Eng, B.Eng Mining, Montana Tech',
        specialization: 'African Mining Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Dennis Stansbury',
        title: 'Vice President, Exploration',
        yearsAtCompany: 8.1,
        previousCompanies: ['Volta Resources', 'Newmont Mining'],
        education: 'M.Sc Geology, University of Nevada, Reno',
        specialization: 'West African Gold Exploration',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'NGD',
    executives: [
      {
        name: 'Patrick Carusone',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 3.2,
        previousCompanies: ['Barrick Gold', 'Tahoe Resources'],
        education: 'MBA, Schulich School of Business; P.Eng',
        specialization: 'Canadian Gold Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Anna Marks',
        title: 'Chief Financial Officer',
        yearsAtCompany: 2.8,
        previousCompanies: ['Yamana Gold', 'CIBC Capital Markets'],
        education: 'CPA, Queen\'s University',
        specialization: 'Mining Corporate Finance & Treasury',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Rob Chaudhry',
        title: 'Chief Operating Officer',
        yearsAtCompany: 4.5,
        previousCompanies: ['IAMGOLD', 'Teck Resources'],
        education: 'P.Eng, B.Eng Mining, University of Toronto',
        specialization: 'Block Cave & Underground Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'IMG',
    executives: [
      {
        name: 'Renaud Adams',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 4.6,
        previousCompanies: ['New Gold Inc.', 'Richfield Mining', 'Noranda'],
        education: 'B.Eng Mining, Ecole Polytechnique de Montreal',
        specialization: 'Gold Mine Construction & Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Maarten Fregeau',
        title: 'Executive Vice President & Chief Financial Officer',
        yearsAtCompany: 3.9,
        previousCompanies: ['Stornoway Diamond', 'PricewaterhouseCoopers'],
        education: 'CPA, Universite Laval',
        specialization: 'Mining Project Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Bruno Lemelin',
        title: 'Senior Vice President, Operations',
        yearsAtCompany: 6.7,
        previousCompanies: ['Agnico Eagle', 'ArcelorMittal Mining'],
        education: 'P.Eng, B.Eng Mechanical, Universite de Sherbrooke',
        specialization: 'Large-Scale Open-Pit Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Craig MacDougall',
        title: 'Senior Vice President, Exploration',
        yearsAtCompany: 5.2,
        previousCompanies: ['Goldcorp', 'Probe Metals'],
        education: 'M.Sc Geology, Laurentian University',
        specialization: 'Canadian Shield Gold Exploration',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'MND',
    executives: [
      {
        name: 'Frazer Bourchier',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 5.1,
        previousCompanies: ['Kirkland Lake Gold', 'St Andrew Goldfields'],
        education: 'P.Eng, B.Eng Mining, Laurentian University',
        specialization: 'Underground Gold-Antimony Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Edward Muia',
        title: 'Chief Financial Officer',
        yearsAtCompany: 3.4,
        previousCompanies: ['Lundin Gold', 'KPMG Australia'],
        education: 'CPA, University of Melbourne',
        specialization: 'International Mining Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Chris Davis',
        title: 'Vice President, Operations',
        yearsAtCompany: 4.7,
        previousCompanies: ['Newcrest Mining', 'Barrick Gold Australia'],
        education: 'B.Eng Mining, Curtin University',
        specialization: 'Australian Underground Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'LUG',
    executives: [
      {
        name: 'Ron Hochstein',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 8.3,
        previousCompanies: ['Tahoe Resources', 'Pan American Silver', 'HudBay Minerals'],
        education: 'P.Eng, MBA, University of British Columbia',
        specialization: 'Latin American Gold Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Alessandro Bitelli',
        title: 'Chief Financial Officer',
        yearsAtCompany: 5.9,
        previousCompanies: ['Tahoe Resources', 'BDO International'],
        education: 'CPA, CFA, McGill University',
        specialization: 'Mining Finance & Ecuadorian Tax',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Andre Oliveira',
        title: 'Vice President, Operations',
        yearsAtCompany: 6.1,
        previousCompanies: ['SolGold', 'Kinross Gold Ecuador'],
        education: 'B.Eng Mining, Universidade Federal do Rio de Janeiro',
        specialization: 'Underground Mining & Paste Backfill',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Nathan Monash',
        title: 'Vice President, Exploration',
        yearsAtCompany: 4.2,
        previousCompanies: ['Newcrest Mining', 'SolGold Ecuador'],
        education: 'M.Sc Geology, University of Tasmania',
        specialization: 'Epithermal Gold-Silver Deposits',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'KRR',
    executives: [
      {
        name: 'Paul Shortridge',
        title: 'Chief Executive Officer & Managing Director',
        yearsAtCompany: 3.8,
        previousCompanies: ['St Barbara Ltd.', 'Gold Fields'],
        education: 'MBA, University of Western Australia',
        specialization: 'Western Australian Gold Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Tony Makuch',
        title: 'Non-Executive Chairman',
        yearsAtCompany: 2.5,
        previousCompanies: ['Kirkland Lake Gold (CEO)', 'Lake Shore Gold', 'FNX Mining'],
        education: 'P.Eng, B.Eng Mining, Laurentian University',
        specialization: 'High-Grade Gold Mine Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Mark Gunderson',
        title: 'Chief Financial Officer',
        yearsAtCompany: 4.1,
        previousCompanies: ['Westgold Resources', 'Deloitte Australia'],
        education: 'CPA, University of Western Australia',
        specialization: 'Australian Mining Finance & Compliance',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'RIO',
    executives: [
      {
        name: 'Alex Black',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 9.7,
        previousCompanies: ['Rio Cristal Resources', 'Mandalay Resources'],
        education: 'P.Geo, B.Sc Geology, University of British Columbia',
        specialization: 'Heap Leach Gold Project Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Brian Groves',
        title: 'Chief Financial Officer',
        yearsAtCompany: 5.3,
        previousCompanies: ['Trevali Mining', 'Grant Thornton'],
        education: 'CPA, University of British Columbia',
        specialization: 'Junior Mining Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Catrina Klippenstein',
        title: 'Vice President, Permitting & Sustainability',
        yearsAtCompany: 4.8,
        previousCompanies: ['Barrick Gold Chile', 'SNC-Lavalin'],
        education: 'M.Sc Environmental Science, Universidad de Chile',
        specialization: 'Environmental Permitting in Chile',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'SBB',
    executives: [
      {
        name: 'Bruce McLeod',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 7.6,
        previousCompanies: ['Mercator Minerals', 'Terrane Metals', 'Thompson Creek Metals'],
        education: 'P.Eng, B.Eng Mining, University of British Columbia',
        specialization: 'Arctic Mining & Project Development',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Elaine Bennett',
        title: 'Vice President, Finance & Chief Financial Officer',
        yearsAtCompany: 5.4,
        previousCompanies: ['Imperial Metals', 'Deloitte'],
        education: 'CPA, University of British Columbia',
        specialization: 'Mining Construction Finance',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Matt Dufresne',
        title: 'Vice President, Exploration',
        yearsAtCompany: 8.9,
        previousCompanies: ['Miramar Mining', 'Newmont Mining'],
        education: 'P.Geo, M.Sc Geology, University of Alberta',
        specialization: 'Iron Formation-Hosted Gold Deposits',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Richard Brissenden',
        title: 'Vice President, Project Development',
        yearsAtCompany: 6.2,
        previousCompanies: ['De Beers Canada', 'SNC-Lavalin'],
        education: 'P.Eng, B.Eng Civil, Dalhousie University',
        specialization: 'Arctic Infrastructure & Construction',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'GPL',
    executives: [
      {
        name: 'Simon Marcotte',
        title: 'Interim Chief Executive Officer',
        yearsAtCompany: 1.8,
        previousCompanies: ['Fortuna Silver Mines', 'Pan American Silver'],
        education: 'MBA, McGill University',
        specialization: 'Silver Mining & Corporate Restructuring',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Jim Fisk',
        title: 'Chief Financial Officer',
        yearsAtCompany: 2.1,
        previousCompanies: ['Endeavour Silver', 'KPMG'],
        education: 'CPA, University of British Columbia',
        specialization: 'Junior Miner Finance & Restructuring',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Fernando Cavalcanti',
        title: 'Vice President, Operations',
        yearsAtCompany: 3.4,
        previousCompanies: ['Kinross Gold Brazil', 'Vale S.A.'],
        education: 'B.Eng Mining, Universidade Federal de Ouro Preto',
        specialization: 'Brazilian Gold Mining Operations',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'FR',
    executives: [
      {
        name: 'Keith Neumeyer',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 22.4,
        previousCompanies: ['First Quantum Minerals', 'First Silver Reserve'],
        education: 'B.Comm, University of British Columbia',
        specialization: 'Silver Mining & Company Building',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'David Soares',
        title: 'Chief Financial Officer',
        yearsAtCompany: 5.7,
        previousCompanies: ['Tahoe Resources', 'Yamana Gold'],
        education: 'CPA, CFA, University of Toronto',
        specialization: 'Mexican Mining Finance & Hedging',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Todd Anthony',
        title: 'Chief Operating Officer',
        yearsAtCompany: 8.3,
        previousCompanies: ['Coeur Mining', 'Hecla Mining'],
        education: 'P.Eng, B.Eng Mining, Colorado School of Mines',
        specialization: 'Underground Silver-Gold Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Dustin Ferlito',
        title: 'Vice President, Exploration',
        yearsAtCompany: 6.9,
        previousCompanies: ['Endeavour Silver', 'SilverCrest Metals'],
        education: 'M.Sc Geology, University of Arizona',
        specialization: 'Mexican Epithermal Silver Deposits',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
  {
    ticker: 'AG',
    executives: [
      {
        name: 'Keith Neumeyer',
        title: 'President & Chief Executive Officer',
        yearsAtCompany: 22.4,
        previousCompanies: ['First Quantum Minerals', 'First Silver Reserve'],
        education: 'B.Comm, University of British Columbia',
        specialization: 'Silver Mining & Company Building',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'David Soares',
        title: 'Chief Financial Officer',
        yearsAtCompany: 5.7,
        previousCompanies: ['Tahoe Resources', 'Yamana Gold'],
        education: 'CPA, CFA, University of Toronto',
        specialization: 'Mexican Mining Finance & Hedging',
        socialLinkedin: null,
        socialTwitter: null,
      },
      {
        name: 'Todd Anthony',
        title: 'Chief Operating Officer',
        yearsAtCompany: 8.3,
        previousCompanies: ['Coeur Mining', 'Hecla Mining'],
        education: 'P.Eng, B.Eng Mining, Colorado School of Mines',
        specialization: 'Underground Silver-Gold Mining',
        socialLinkedin: null,
        socialTwitter: null,
      },
    ],
  },
];

/**
 * Seed executives into the database.
 * Looks up stock IDs by ticker and inserts 3-5 executives per stock.
 * Skips stocks that are not found in the database.
 */
export async function seedExecutives(): Promise<number> {
  if (!db) {
    console.warn('⚠️  Database not available - skipping executive seed');
    return 0;
  }

  console.log('🌱 Seeding executives...');

  let count = 0;
  for (const stockData of executiveSeedData) {
    // Look up stock ID by ticker
    const stockRows = await db
      .select({ id: stocks.id })
      .from(stocks)
      .where(eq(stocks.ticker, stockData.ticker))
      .limit(1);

    if (stockRows.length === 0) {
      console.warn(`⚠️  Stock ${stockData.ticker} not found - skipping executives`);
      continue;
    }

    const stockId = stockRows[0].id;

    for (const exec of stockData.executives) {
      await db.insert(executives).values({
        stockId,
        name: exec.name,
        title: exec.title,
        yearsAtCompany: exec.yearsAtCompany,
        previousCompanies: exec.previousCompanies,
        education: exec.education,
        specialization: exec.specialization,
        socialLinkedin: exec.socialLinkedin,
        socialTwitter: exec.socialTwitter,
      });
      count++;
    }
  }

  console.log(`✅ Seeded ${count} executives`);
  return count;
}
